pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Course Deals"
include ':app'
include ':core:common'
include ':core:ui'
include ':core:network'
include ':domain:coupons'
include ':domain:user'
include ':data:coupons'
include ':data:user'
include ':feature:home'
include ':feature:profile'
include ':feature:detail'
include ':feature:auth'
include ':feature:splash'
include ':feature:course'
include ':feature:enroll'
