plugins {
    id 'coursedeals.android.library'
    id 'kotlin-parcelize'
}

android {
    namespace 'com.thanh0x.coursedeals.domain.coupons'
}

dependencies {
    implementation project(':core:common')
    implementation project(':domain:user')
    implementation libs.androidx.paging.runtime
    implementation libs.hilt.android
}
