plugins {
    id 'coursedeals.android.library'
    id 'com.google.devtools.ksp'
    id 'dagger.hilt.android.plugin'
}

android {
    namespace 'com.thanh0x.coursedeals.core.ui'
    lint {
        baseline = file("lint-baseline.xml")
    }
}

dependencies {
    api project(':core:common')
    api project(':domain:coupons')
    api libs.androidx.core.ktx
    api libs.androidx.appcompat
    api libs.material
    api libs.androidx.fragment.ktx
    implementation libs.androidx.biometric
    implementation libs.picasso
}
